<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Erasmus Life - About</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="experiences.html">Experiences</a></li>
                <li><a href="resources.html">Resources</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="about">
            <h2>About Me</h2>
            <img src="images/about.jpg" alt="About Image" />
            <p>Welcome to my personal website! I am passionate about international experiences and the positive impact of Erasmus+ programs. Through my journey, I have gained valuable skills in leadership, project management, and intercultural communication.</p>
            <p>Join me as I share my experiences and resources to help you make the most of your Erasmus+ adventure!</p>
        </section>
    </main>

    <footer>
        <p>© 2024 My Erasmus Life. All rights reserved.</p>
    </footer>
</body>
</html>
